export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAILURE = 'CREATE_JOB_FAILURE';

export const JOB_LIST_REQUEST = 'JOB_LIST_REQUEST';
export const JOB_LIST_SUCCESS = 'JOB_LIST_SUCCESS';
export const JOB_LIST_FAILURE = 'JOB_LIST_FAILURE';

export const JOB_DETAILS_REQUEST = 'JOB_DETAILS_REQUEST';
export const JOB_DETAILS_SUCCESS = 'JOB_DETAILS_SUCCESS';
export const JOB_DETAILS_FAILURE = 'JOB_DETAILS_FAILURE';


export const JOB_FILTER_REQUEST = 'JOB_FILTER_REQUEST';
export const JOB_FILTER_SUCCESS = 'JOB_FILTER_SUCCESS';
export const JOB_FILTER_FAILURE = 'JOB_FILTER_FAILURE';