export const MICRO_TRANSACTION_CREATE_REQUEST = 'MICRO_TRANSACTION_CREATE_REQUEST';
export const MICRO_TRANSACTION_CREATE_SUCCESS = 'MICRO_TRANSACTION_CREATE_SUCCESS';
export const MICRO_TRANSACTION_CREATE_FAIL = 'MICRO_TRANSACTION_CREATE_FAIL';

export const MICRO_TRANSACTION_LIST_REQUEST = "MICRO_TRANSACTION_LIST_REQUEST";
export const MICRO_TRANSACTION_LIST_SUCCESS = "MICRO_TRANSACTION_LIST_SUCCESS";
export const MICRO_TRANSACTION_LIST_FAIL = "MICRO_TRANSACTION_LIST_FAIL";

export const MICRO_TRANSACTION_GET_SINGLE_REQUEST = "MICRO_TRANSACTION_GET_SINGLE_REQUEST";
export const MICRO_TRANSACTION_GET_SINGLE_SUCCESS = "MICRO_TRANSACTION_GET_SINGLE_SUCCESS";
export const MICRO_TRANSACTION_GET_SINGLE_FAIL = "MICRO_TRANSACTION_GET_SINGLE_FAIL";


export const MICRO_TRANSACTION_COMPLETE_REQUEST = "MICRO_TRANSACTION_COMPLETE_REQUEST";
export const MICRO_TRANSACTION_COMPLETE_SUCCESS = "MICRO_TRANSACTION_COMPLETE_SUCCESS";
export const MICRO_TRANSACTION_COMPLETE_FAIL = "MICRO_TRANSACTION_COMPLETE_FAIL";
