export const OFFER_LIST_REQUEST = 'OFFER_LIST_REQUEST';
export const OFFER_LIST_SUCCESS = 'OFFER_LIST_SUCCESS';
export const OFFER_LIST_FAIL = 'OFFER_LIST_FAIL';



export const OFFER_CREATE_REQUEST = 'OFFER_CREATE_REQUEST';
export const OFFER_CREATE_SUCCESS = 'OFFER_CREATE_SUCCESS';
export const OFFER_CREATE_FAIL = 'OFFER_CREATE_FAIL';