export const OFFER_LIST_REQUEST = 'OFFER_LIST_REQUEST';
export const OFFER_LIST_SUCCESS = 'OFFER_LIST_SUCCESS';
export const OFFER_LIST_FAIL = 'OFFER_LIST_FAIL';



export const OFFER_CREATE_REQUEST = 'OFFER_CREATE_REQUEST';
export const OFFER_CREATE_SUCCESS = 'OFFER_CREATE_SUCCESS';
export const OFFER_CREATE_FAIL = 'OFFER_CREATE_FAIL';


export const OFFER_SPECIFIC_LIST_REQUEST = 'OFFER_SPECIFIC_LIST_REQUEST';
export const OFFER_SPECIFIC_LIST_SUCCESS = 'OFFER_SPECIFIC_LIST_SUCCESS';
export const OFFER_SPECIFIC_LIST_FAIL = 'OFFER_SPECIFIC_LIST_FAIL';


export const OFFER_CHANGE_STATUS_REQUEST = 'OFFER_CHANGE_STATUS_REQUEST';
export const OFFER_CHANGE_STATUS_SUCCESS = 'OFFER_CHANGE_STATUS_SUCCESS';
export const OFFER_CHANGE_STATUS_FAIL = 'OFFER_CHANGE_STATUS_FAIL';