export const WALLET_GET_BALANCE_REQUEST = 'WALLET_GET_BALANCE_REQUEST';
export const WALLET_GET_BALANCE_SUCCESS = 'WALLET_GET_BALANCE_SUCCESS';
export const WALLET_GET_BALANCE_FAIL = 'WALLET_GET_BALANCE_FAIL';