export const WORK_SUBMIT_REQUEST = 'WORK_SUBMIT_REQUEST';
export const WORK_SUBMIT_SUCCESS = 'WORK_SUBMIT_SUCCESS';
export const WORK_SUBMIT_FAIL = 'WORK_SUBMIT_FAIL';

export const WORK_FILTER_REQUEST = 'WORK_FILTER_REQUEST';
export const WORK_FILTER_SUCCESS = 'WORK_FILTER_SUCCESS';
export const WORK_FILTER_FAIL = 'WORK_FILTER_FAIL';


export const GET_WORK_REQUEST = 'GET_WORK_REQUEST';
export const GET_WORK_SUCCESS = 'GET_WORK_SUCCESS';
export const GET_WORK_FAIL = 'GET_WORK_FAIL';


