export const YOUTUBE_REQUEST_SENDING = 'YOUTUBE_REQUEST_SENDING';
export const YOUTUBE_REQUEST_SUCCESS = 'YOUTUBE_REQUEST_SUCCESS';
export const YOUTUBE_REQUEST_FAILED = 'YOUTUBE_REQUEST_FAILED';

export const YOUTUBE_CHECK_REQUEST_SENDING = 'YOUTUBE_CHECK_REQUEST_SENDING';
export const YOUTUBE_CHECK_REQUEST_SUCCESS = 'YOUTUBE_CHECK_REQUEST_SUCCESS';
export const YOUTUBE_CHECK_REQUEST_FAILED = 'YOUTUBE_CHECK_REQUEST_FAILED';


export const YOUTUBE_GET_CODE = 'YOUTUBE_GET_CODE';
export const YOUTUBE_GET_CODE_SUCCESS = 'YOUTUBE_GET_CODE_SUCCESS';
export const YOUTUBE_GET_CODE_FAILED = 'YOUTUBE_GET_CODE_FAILED';