export const YOUTUBE_REQUEST_SENDING = 'YOUTUBE_REQUEST_SENDING';
export const YOUTUBE_REQUEST_SUCCESS = 'YOUTUBE_REQUEST_SUCCESS';
export const YOUTUBE_REQUEST_FAILED = 'YOUTUBE_REQUEST_FAILED';

export const YOUTUBE_CHECK_REQUEST_SENDING = 'YOUTUBE_CHECK_REQUEST_SENDING';
export const YOUTUBE_CHECK_REQUEST_SUCCESS = 'YOUTUBE_CHECK_REQUEST_SUCCESS';
export const YOUTUBE_CHECK_REQUEST_FAILED = 'YOUTUBE_CHECK_REQUEST_FAILED';
